name: Automation CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, closed]

jobs:
  git-flow:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Clone and checkout repository
        uses: actions/checkout@v2

      - name: List out repo content
        run: |
          ls -la
