name: JavaScript Automation CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, closed]

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Clone and checkout repository
        run: |
          git clone https://github.com/${{ github.repository }} repo
          cd repo
          branch_name=${GITHUB_REF#refs/heads/}
          git checkout ${branch_name}

      - name: List out repo content
        run: |
          cd repo && ls -la

      - name: List out default variables
        run: env
